export default {
    CREATE_CATEGORY:"CREATE_CATEGORY",
    CREATE_LOCATION:"CREATE_LOCATION",

    UPDATE_CATEGORY:"UPDATE_CATEGORY",
    UPDATE_LOCATION:"UPDATE_LOCATION",

    DELETE_CATEGORY:"DELETE_CATEGORY",
    DELETE_LOCATION:"DELETE_LOCATION"
};